Repository projectsyn/component-grafana-helm, pull requests merged in 2022-09, with the labels that each got.

#26 Enable golden and matrix tests
  .cruft.json
  .editorconfig
  .github/workflows/test.yaml
  Makefile
  Makefile.vars.mk
  renovate.json
  tests/defaults.yml
  tests/golden/defaults/grafana-helm/apps/grafana-helm.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/00_namespace.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/clusterrole.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/clusterrolebinding.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/configmap.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/deployment.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/podsecuritypolicy.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/role.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/rolebinding.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/secret.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/service.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/serviceaccount.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/servicemonitor.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/grafana-extraconfigmap.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/grafana-resources/01_datasources.yaml
Labels: change

#27 Allow multi instantiation of the component
  class/defaults.yml
  class/grafana-helm.yml
  component/app.jsonnet
Labels: enhancement

#28 Allow setting namespace metadata
  class/defaults.yml
  component/main.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
Labels: enhancement

#29 Fix `app` compilation
  component/app.jsonnet
Labels: ignore

#30 Add facility to generate secrets
  class/defaults.yml
  component/main.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/defaults.yml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/deployment.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/secret.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/10_secrets.yaml
Labels: enhancement

#31 Update Helm release grafana to v6.38.6
  class/defaults.yml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/clusterrole.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/clusterrolebinding.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/configmap.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/deployment.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/role.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/rolebinding.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/service.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/serviceaccount.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/servicemonitor.yaml
Labels: dependency
