Repository projectsyn/component-grafana-helm, pull requests merged in 2025-01, with the labels that each got.

#58 Update from component template
  .cruft.json
  class/defaults.yml
  class/grafana-helm.yml
  component/app.jsonnet
Labels: template-sync

#57 Update Helm release grafana to v8.8.2
  class/defaults.yml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/clusterrole.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/clusterrolebinding.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/configmap.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/deployment.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/role.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/rolebinding.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/service.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/serviceaccount.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/servicemonitor.yaml
Labels: dependency, bump:minor

#59 Update Helm release grafana to v8.8.3
  class/defaults.yml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/clusterrole.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/clusterrolebinding.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/configmap.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/deployment.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/role.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/rolebinding.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/service.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/serviceaccount.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/servicemonitor.yaml
Labels: dependency, automerge, bump:patch

#60 Update Helm release grafana to v8.8.4
  class/defaults.yml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/clusterrole.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/clusterrolebinding.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/configmap.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/deployment.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/role.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/rolebinding.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/service.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/serviceaccount.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/servicemonitor.yaml
Labels: dependency, automerge, bump:patch

#61 Update Helm release grafana to v8.8.5
  class/defaults.yml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/clusterrole.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/clusterrolebinding.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/configmap.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/deployment.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/role.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/rolebinding.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/service.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/serviceaccount.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/servicemonitor.yaml
Labels: dependency, automerge, bump:patch

#62 Update Helm release grafana to v8.8.6
  class/defaults.yml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/clusterrole.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/clusterrolebinding.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/configmap.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/deployment.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/role.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/rolebinding.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/service.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/serviceaccount.yaml
  tests/golden/defaults/grafana-helm/grafana-helm/01_helmchart/grafana/templates/servicemonitor.yaml
Labels: dependency, automerge, bump:patch
